// <auto-generated />
using System;
using Elara1.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elara1.DataAccess.Migrations
{
    [DbContext(typeof(ElaraDbContext))]
    [Migration("20260819103736_AddCreatedAt")]
    partial class AddCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elara1.DataAccess.Memory.MemoryFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MemoryFacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "User works as a software engineer at a tech firm.",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 37, 35, 879, DateTimeKind.Utc).AddTicks(1848)
                        },
                        new
                        {
                            Id = 2,
                            Content = "User's partner is named Alex.",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 37, 35, 879, DateTimeKind.Utc).AddTicks(1849)
                        },
                        new
                        {
                            Id = 3,
                            Content = "User tends to feel overwhelmed when deadlines pile up on Fridays.",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 37, 35, 879, DateTimeKind.Utc).AddTicks(1849)
                        },
                        new
                        {
                            Id = 4,
                            Content = "User's favorite way to relax is going for evening walks.",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 37, 35, 879, DateTimeKind.Utc).AddTicks(1850)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
